#
#   ┏━━━━━━━━━━━━━━━━━━━━━━━━ ⊹ ☆ ⊹ ━━━━━━━━━━━━━━━━━━━━━━━━┓
#
#                      Various Permissions
#      Source: https://github.com/WIX3Y/VariousPermissions
#                          Author: WIX3Y
#
#   ┗━━━━━━━━━━━━━━━━━━━━━━━━ ⊹ ☆ ⊹ ━━━━━━━━━━━━━━━━━━━━━━━━┛
#
#   ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
#
#                      List of Placeholders
#
#     VP_has_item_amount_<material>_<namespace>_<key>_<amount>
#  True if the player has at least the amount of the specified item
#  Example usage: %VP_has_item_amount_STICK_mynamespace_mymodel_2%
#
#
#   ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
#
#   ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
#
#                        List of Commands
#
#                          vppermission
#        Get the permission required to use the held item
#      Required permission: variouspermissions.getpermission
#                 Example usage: /vppermission
#
#  vptakeitem <player> <material> <item-model-namespace> <item-model-key> <amount>
#       Take an item with specified item model from a player
#      Required permission: variouspermissions.takeitem
#  Example usage: /vptakeitem WIX3Y STICK mynamespace mymodel 2
#
#   ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
#

# Do not change
config-version: 1